// Generated by scripts/download_and_embed_assets.js - do not edit manually
// Run: node scripts/download_and_embed_assets.js

class Rating {
  final String code;
  final String name;
  final String assetPath;
  final bool disabled;

  const Rating({
    required this.code,
    required this.name,
    required this.assetPath,
    this.disabled = false,
  });
}

const List<Rating> ratings = [
  Rating(
    code: 'agree',
    name: 'Agree',
    assetPath: 'assets/ratings/rating-agree.png',
    disabled: false,
  ),
  Rating(
    code: 'disagree',
    name: 'Disagree',
    assetPath: 'assets/ratings/rating-disagree.png',
    disabled: false,
  ),
  Rating(
    code: 'funny',
    name: 'Funny',
    assetPath: 'assets/ratings/rating-funny.png',
    disabled: false,
  ),
  Rating(
    code: 'friendly',
    name: 'Friendly',
    assetPath: 'assets/ratings/rating-friendly.png',
    disabled: false,
  ),
  Rating(
    code: 'kawaii',
    name: 'Kawaii',
    assetPath: 'assets/ratings/rating-cute.png',
    disabled: false,
  ),
  Rating(
    code: 'sad',
    name: 'Sad',
    assetPath: 'assets/ratings/rating-sad.png',
    disabled: false,
  ),
  Rating(
    code: 'artistic',
    name: 'Creative',
    assetPath: 'assets/ratings/rating-artistic.png',
    disabled: false,
  ),
  Rating(
    code: 'informative',
    name: 'Informative',
    assetPath: 'assets/ratings/rating-informative.png',
    disabled: false,
  ),
  Rating(
    code: 'idea',
    name: 'Idea',
    assetPath: 'assets/ratings/rating-idea.png',
    disabled: false,
  ),
  Rating(
    code: 'winner',
    name: 'Winner',
    assetPath: 'assets/ratings/rating-winner.png',
    disabled: false,
  ),
  Rating(
    code: 'glasses',
    name: 'Bad Reading',
    assetPath: 'assets/ratings/rating-badreading.png',
    disabled: false,
  ),
  Rating(
    code: 'late',
    name: 'Late',
    assetPath: 'assets/ratings/rating-late.png',
    disabled: false,
  ),
  Rating(
    code: 'dumb',
    name: 'Dumb',
    assetPath: 'assets/ratings/rating-dumb.png',
    disabled: true,
  ),
  Rating(
    code: 'citation',
    name: 'Citation Needed',
    assetPath: 'assets/ratings/rating-citation.png',
    disabled: false,
  ),
  Rating(
    code: 'optimistic',
    name: 'Optimistic',
    assetPath: 'assets/ratings/rating-optimistic.png',
    disabled: false,
  ),
  Rating(
    code: 'zing',
    name: 'Zing',
    assetPath: 'assets/ratings/rating-zing.png',
    disabled: false,
  ),
  Rating(
    code: 'yeet',
    name: 'Yeet',
    assetPath: 'assets/ratings/rating-yeet.png',
    disabled: false,
  ),
  Rating(
    code: 'rude',
    name: 'Rude',
    assetPath: 'assets/ratings/rating-rude.png',
    disabled: false,
  ),
  Rating(
    code: 'confusing',
    name: 'Confusing',
    assetPath: 'assets/ratings/rating-confusing.png',
    disabled: false,
  ),
  Rating(
    code: 'scary',
    name: 'Scary',
    assetPath: 'assets/ratings/rating-scary.png',
    disabled: false,
  ),
];

/// Lookup a rating by code, returns null if not found
Rating? getRatingByCode(String code) {
  return ratings.where((r) => r.code == code).firstOrNull;
}

/// Get all enabled ratings
List<Rating> get enabledRatings =>
    ratings.where((r) => !r.disabled).toList();

/// Map of rating codes to ratings for fast lookup
final Map<String, Rating> ratingMap = {
  for (final r in ratings) r.code: r,
};
